import TheHeader from "@/components/TheHeader/TheHeader";



export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function Layout({ children }) {
  return (
    <>
      <TheHeader />
      {children}
    </>
  );
}
