import TheHeader from '@/components/TheHeader/TheHeader';
import './globals.css'
import localFont from "next/font/local";

const replica = localFont({
  src: [
    {
      path: "../../public/assets/fonts/ReplicaMonoLL-Regular.otf",
      weight: "300",
      style: "normal",
      variable: "--font-replica-mono",
    },
    {
      path: "../../public/assets/fonts/ReplicaLL-Light.otf",
      weight: "300",
      style: "normal",
      variable: "--font-replica",
    },
    {
      path: "../../public/assets/fonts/ReplicaLL-LightItalic.otf",
      weight: "300",
      style: "italic",
      variable: "--font-replica",
    },
    {
      path: "../../public/assets/fonts/ReplicaLL-Regular.otf",
      weight: "400",
      style: "normal",
      variable: "--font-replica",
    },
    {
      path: "../../public/assets/fonts/ReplicaLL-RegularItalic.otf",
      weight: "400",
      style: "italic",
      variable: "--font-replica",
    },
    {
      path: "../../public/assets/fonts/ReplicaLL-Bold.otf",
      weight: "700",
      style: "normal",
      variable: "--font-replica",
    },
    {
      path: "../../public/assets/fonts/ReplicaLL-BoldItalic.otf",
      weight: "700",
      style: "italic",
      variable: "--font-replica",
    },
    {
      path: "../../public/assets/fonts/ReplicaLL-Heavy.otf",
      weight: "900",
      style: "normal",
      variable: "--font-replica",
    },
    {
      path: "../../public/assets/fonts/ReplicaLL-HeavyItalic.otf",
      weight: "900",
      style: "italic",
      variable: "--font-replica",
    },
  ],
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={replica.className}>
          <TheHeader />
          <main>{children}</main>
      </body>
    </html>
  );
}
